# Generated by Django 4.2 on 2023-05-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('voyageDate', models.DateTimeField()),
                ('prix', models.IntegerField()),
                ('nmbPlace', models.IntegerField()),
            ],
        ),
    ]
