# Generated by Django 4.2 on 2023-05-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_voyage_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
