# Generated by Django 4.2 on 2023-05-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_messages_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='messages',
        ),
    ]
