# Generated by Django 4.2 on 2023-05-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='mess',
        ),
    ]
